spring:
  application:
    name: ciyex
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://aran.apps-dev.in.hinisoft.com/realms/master
          jwk-set-uri: https://aran.apps-dev.in.hinisoft.com/realms/master/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
jwt:
  secret: Um7I76bdvjLLGMWPPYYZr4jYXSNKpHOtIQS8Ktg8C4w=
  expiration: 31557600000
keycloak:
  enabled: ${KEYCLOAK_ENABLED:false}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:https://aran.apps-dev.in.hinisoft.com}
  realm: ${KEYCLOAK_REALM:master}
  resource: ${KEYCLOAK_RESOURCE:ciyex-app}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:LgDl38nUg6leUfB9DCG5LDglC75bxpOp}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:aran-admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:Kc@2024!Secure#Pass}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
logging:
  level:
    root: info
    com.qiaben.ciyex.audit: debug
fhir:
  server:
    url: ${FHIR_SERVER_URL:https://fhir.apps-dev.in.hinisoft.com/fhir}
  client:
    socket-timeout: 60000
    connect-timeout: 10000
ciyex:
  env: ${CIYEX_ENV:local}
  schema:
    name: ${CIYEX_SCHEMA_NAME:public}
  audit:
    enabled: true
  super-admin:
    orgs: ${CIYEX_SUPER_ADMIN_ORGS:hinisoft-dev}
