spring:
  application:
    name: ciyex
  datasource:
    url: jdbc:mysql://localhost:3306/ciyexdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: Um7I76bdvjLLGMWPPYYZr4jYXSNKpHOtIQS8Ktg8C4w=
  expiration: 31557600000

cors:
  allowed-origins: http://localhost:3000

logging:
  level:
    root: info
